name: PurePlay-Research-Kit
channels:
  - conda-forge
  - defaults
dependencies:
  # --- Base Dependencies ---
  - python=3.11     # Eventually update to >=3.14
  - pip

  # --- Conda Packages ---
  - pydantic
  - pydantic-settings
  - pywin32
  - pyarrow
  - pyarrow-stubs
  - pandas
  - polars
  - pytorch-gpu
  - lightning
  - lightning[extra]
  - tensorboard
  - optuna
  - optuna-integration
  - plotly
  - scikit-learn
  - blinker

  # --- Pip Packages ---
  - pip:
    - sk2torch       # Replace by hummingbird-ml or nvtabular for >=3.14
    - XInput-Python  # Replace when updating to >=3.14
    - keyboard       # This should ideally mean I can get rid
    - mouse          # of bind enums and windows_raw_mouse.