[workspace]
name = "PurePlay-Research-Kit"
description = "Free, Open-Source Tool for Anti-Cheat Research and Development"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[dependencies]
python = "==3.11"
blinker = "*"
pydantic = "*"
pydantic-settings = "*"
pynput = "*"
pygame = "*"
pyarrow = "*"
pyarrow-stubs = "*"
pandas = "*"
polars = "*"
pytorch = "*"
lightning = "*"
optuna = "*"
optuna-integration = "*"
scikit-learn = "*"
tensorboard = "*"
plotly = "*"

[target.win-64.dependencies]
pywin32 = "*"
cuda-toolkit = "*"
cudnn = "*"

[target.linux-64.dependencies]
evdev = "*"
cuda-toolkit = "*"
cudnn = "*"

[pypi-dependencies]
sk2torch = "*"  # Replace with hummingbird-ml or nvtabular for >=3.14

[tasks]
gui-app = "python source/main.py -use_gui"
cli-app = "python source/main.py"
