# Pre-Training
BATCH_SIZE_TUNE_EPOCHS = 50

# Early Stopping
EARLY_STOPPING_PATIENCE = 20
EARLY_STOPPING_DELTA = 0.0001

# Hyperparameters
HIDDEN_SIZE_MIN = 16
LATENT_SIZE_MIN = 8
HIDDEN_LAYERS_MIN = 1
HIDDEN_LAYERS_MAX = 4
DROPOUT_MIN = 0.0
DROPOUT_MAX = 0.5
LEARNING_RATE_MIN = 1e-6
LEARNING_RATE_MAX = 1e-3
WEIGHT_DECAY_MIN = 1e-6
WEIGHT_DECAY_MAX = 1e-3
MOMENTUM_MIN = 0.0
MOMENTUM_MAX = 0.99

# Stochastic Weight Averaging
SWA_EPOCH_START_MIN = 20
SWA_EPOCH_START_MAX = 2000
SWA_LR_FACTOR_MIN = 0.05
SWA_LR_FACTOR_MAX = 0.8